apiVersion: v2
name: matrixone-operator
description: Matrixone Kubernetes Operator
type: application
version: 0.8.0-alpha.7
appVersion: 0.1.0
kubeVersion: ">=1.19.0-0"
icon: https://raw.githubusercontent.com/matrixorigin/artwork/main/docs/overview/logo.png
dependencies:
  - name: kruise
    version: "1.4.0"
    repository: "https://openkruise.github.io/charts/"
