apiVersion: v1
entries:
  matrixone-operator:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-02-28T15:56:39.994503+08:00"
    description: MatrixOne Operator
    digest: cf738d71dc843c50331200a099b81b8cecec1d68251343df2d5b0aa45b2a3d14
    name: matrixone-operator
    type: application
    urls:
    - ./matrixone-operator/0.1.0
    version: 0.1.0
generated: "2022-02-28T15:56:39.993076+08:00"
